# Generated by Django 4.2.7 on 2025-05-31 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='عنوان المحادثة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'محادثة',
                'verbose_name_plural': 'المحادثات',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_title', models.CharField(max_length=200, verbose_name='العنوان المقترح')),
                ('suggested_description', models.TextField(blank=True, verbose_name='الوصف المقترح')),
                ('suggested_category', models.CharField(blank=True, max_length=100, verbose_name='التصنيف المقترح')),
                ('suggested_priority', models.CharField(blank=True, max_length=10, verbose_name='الأولوية المقترحة')),
                ('suggested_due_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاستحقاق المقترح')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='تم القبول')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ai_assistant.conversation', verbose_name='المحادثة')),
                ('created_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.task', verbose_name='المهمة المنشأة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'اقتراح مهمة',
                'verbose_name_plural': 'اقتراحات المهام',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('user', 'مستخدم'), ('assistant', 'مساعد'), ('system', 'نظام')], max_length=10, verbose_name='نوع الرسالة')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ai_messages/', verbose_name='صورة')),
                ('tokens_used', models.PositiveIntegerField(default=0, verbose_name='الرموز المستخدمة')),
                ('response_time', models.FloatField(default=0.0, verbose_name='وقت الاستجابة (ثانية)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_assistant.conversation', verbose_name='المحادثة')),
            ],
            options={
                'verbose_name': 'رسالة',
                'verbose_name_plural': 'الرسائل',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIUsageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_conversations', models.PositiveIntegerField(default=0, verbose_name='إجمالي المحادثات')),
                ('total_messages', models.PositiveIntegerField(default=0, verbose_name='إجمالي الرسائل')),
                ('total_tokens_used', models.PositiveIntegerField(default=0, verbose_name='إجمالي الرموز المستخدمة')),
                ('total_images_analyzed', models.PositiveIntegerField(default=0, verbose_name='إجمالي الصور المحللة')),
                ('daily_messages_count', models.PositiveIntegerField(default=0, verbose_name='عدد الرسائل اليومية')),
                ('last_reset_date', models.DateField(auto_now_add=True, verbose_name='تاريخ آخر إعادة تعيين')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إحصائيات الاستخدام',
                'verbose_name_plural': 'إحصائيات الاستخدام',
            },
        ),
    ]
